Name: ticket-worker
Host: 0.0.0.0
Port: 8084
Timeout: 5000

Mysql:
  Dsn: "root:root@tcp(mysql:3306)/ticketing?parseTime=true"
Redis:
  Addr: "redis:6379"
  Password: ""
  DB: 0
Kafka:
  Brokers:
    - "kafka:9092"

SeatAllocatorMode: "mock"
SeatAllocatorAddr: "seat-allocator:50051"
SeatAllocatorTrainID: "G123"
SeatAllocatorTravelDate: "2026-02-11"
SeatAllocatorCoachType: "2nd"
SeatAllocatorFromIndex: 1
SeatAllocatorToIndex: 3


