global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: "order-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["order-service:8081"]

  - job_name: "inventory-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["inventory-service:8082"]

  - job_name: "query-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["query-service:8083"]

  - job_name: "ticket-worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["ticket-worker:8084"]


